// This file is generated by `node scripts/generate-states.mjs`.
// Do not edit by hand.

export type MediaRef = {
  file: string
  url: string
  source: 'Wikimedia Commons'
}

export type USStateGenerated = {
  id: string
  slug: string
  name: string
  abbreviation: string
  capital: string
  isoCode: string | null
  wikidataQid: string
  commonsCategory: string | null
  flag: MediaRef | null
  seal: MediaRef | null
  heroVideo: MediaRef | null
  heroPhoto: MediaRef | null
}

export const US_STATES_GENERATED: USStateGenerated[] = [
  {
    "id": "al",
    "slug": "al",
    "name": "Alabama",
    "abbreviation": "AL",
    "capital": "Montgomery",
    "isoCode": "US-AL",
    "wikidataQid": "Q173",
    "commonsCategory": "Alabama",
    "flag": {
      "file": "File:Flag of Alabama.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Alabama.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Alabama.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Alabama.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1868 United States Presidential Election in Alabama Map by County.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1868%20United%20States%20Presidential%20Election%20in%20Alabama%20Map%20by%20County.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ak",
    "slug": "ak",
    "name": "Alaska",
    "abbreviation": "AK",
    "capital": "Juneau",
    "isoCode": "US-AK",
    "wikidataQid": "Q797",
    "commonsCategory": "Alaska",
    "flag": {
      "file": "File:Flag of Alaska.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Alaska.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of the State of Alaska.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20the%20State%20of%20Alaska.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Alaska Red Fox (Vulpes vulpes).jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Alaska%20Red%20Fox%20(Vulpes%20vulpes).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "az",
    "slug": "az",
    "name": "Arizona",
    "abbreviation": "AZ",
    "capital": "Phoenix",
    "isoCode": "US-AZ",
    "wikidataQid": "Q816",
    "commonsCategory": "Arizona",
    "flag": {
      "file": "File:Flag of Arizona.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Arizona.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:State Seal of Arizona.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/State%20Seal%20of%20Arizona.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Arizona (BB39) Port Bow, Underway - NARA - 5900075 - 1930.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Arizona%20(BB39)%20Port%20Bow%2C%20Underway%20-%20NARA%20-%205900075%20-%201930.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ar",
    "slug": "ar",
    "name": "Arkansas",
    "abbreviation": "AR",
    "capital": "Little Rock",
    "isoCode": "US-AR",
    "wikidataQid": "Q1612",
    "commonsCategory": "Arkansas",
    "flag": {
      "file": "File:Flag of Arkansas.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Arkansas.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Arkansas.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Arkansas.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2002-2008 Arkansas United States House of Representatives election by Congressional District.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2002-2008%20Arkansas%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ca",
    "slug": "ca",
    "name": "California",
    "abbreviation": "CA",
    "capital": "Sacramento",
    "isoCode": "US-CA",
    "wikidataQid": "Q99",
    "commonsCategory": "California",
    "flag": {
      "file": "File:Flag of California.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20California.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of California.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20California.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": {
      "file": "File:Social distancing video by California State Parks.ogv",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Social%20distancing%20video%20by%20California%20State%20Parks.ogv",
      "source": "Wikimedia Commons"
    },
    "heroPhoto": {
      "file": "File:Amboy (California, USA) -- 2012 -- 4.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Amboy%20(California%2C%20USA)%20--%202012%20--%204.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "co",
    "slug": "co",
    "name": "Colorado",
    "abbreviation": "CO",
    "capital": "Denver",
    "isoCode": "US-CO",
    "wikidataQid": "Q1261",
    "commonsCategory": "Colorado",
    "flag": {
      "file": "File:Flag of Colorado.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Colorado.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Colorado.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Colorado.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": {
      "file": "File:Aerial views of Mohawk Lake, Breckenridge, Colorado, United States of America.webm",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20views%20of%20Mohawk%20Lake%2C%20Breckenridge%2C%20Colorado%2C%20United%20States%20of%20America.webm",
      "source": "Wikimedia Commons"
    },
    "heroPhoto": {
      "file": "File:2012-11-09 01 Independent Monument at Colorado National Monument.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2012-11-09%2001%20Independent%20Monument%20at%20Colorado%20National%20Monument.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ct",
    "slug": "ct",
    "name": "Connecticut",
    "abbreviation": "CT",
    "capital": "Hartford",
    "isoCode": "US-CT",
    "wikidataQid": "Q779",
    "commonsCategory": "Connecticut",
    "flag": {
      "file": "File:Flag of Connecticut.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Connecticut.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Connecticut.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Connecticut.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1713 border map of Massachusetts and Connecticut.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1713%20border%20map%20of%20Massachusetts%20and%20Connecticut.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "de",
    "slug": "de",
    "name": "Delaware",
    "abbreviation": "DE",
    "capital": "Dover",
    "isoCode": "US-DE",
    "wikidataQid": "Q1393",
    "commonsCategory": "Delaware",
    "flag": {
      "file": "File:Flag of Delaware.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Delaware.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Delaware.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Delaware.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2022-07-15 17 39 04 View south along Delaware State Route 1 (Korean War Veterans Memorial Highway) from the overpass for White Oak Road in Dover, Kent County, Delaware.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2022-07-15%2017%2039%2004%20View%20south%20along%20Delaware%20State%20Route%201%20(Korean%20War%20Veterans%20Memorial%20Highway)%20from%20the%20overpass%20for%20White%20Oak%20Road%20in%20Dover%2C%20Kent%20County%2C%20Delaware.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "dc",
    "slug": "dc",
    "name": "District of Columbia",
    "abbreviation": "DC",
    "capital": "Washington, D.C.",
    "isoCode": "US-DC",
    "wikidataQid": "Q61",
    "commonsCategory": "Washington, D.C.",
    "flag": {
      "file": "File:Flag of the District of Columbia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20the%20District%20of%20Columbia.svg",
      "source": "Wikimedia Commons"
    },
    "seal": null,
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:\"The Holocaust Victims \"United States Holocaust Memorial Museum.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/%22The%20Holocaust%20Victims%20%22United%20States%20Holocaust%20Memorial%20Museum.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "fl",
    "slug": "fl",
    "name": "Florida",
    "abbreviation": "FL",
    "capital": "Tallahassee",
    "isoCode": "US-FL",
    "wikidataQid": "Q812",
    "commonsCategory": "Florida",
    "flag": {
      "file": "File:Flag of Florida.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Florida.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Florida.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Florida.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2025 Florida Drought Map.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2025%20Florida%20Drought%20Map.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ga",
    "slug": "ga",
    "name": "Georgia",
    "abbreviation": "GA",
    "capital": "Atlanta",
    "isoCode": "US-GA",
    "wikidataQid": "Q1428",
    "commonsCategory": "Georgia (U.S. state)",
    "flag": {
      "file": "File:Flag of the State of Georgia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20the%20State%20of%20Georgia.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Georgia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Georgia.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:A Bojangles fast food restaurant in Hiawassee, Georgia, United States 01.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/A%20Bojangles%20fast%20food%20restaurant%20in%20Hiawassee%2C%20Georgia%2C%20United%20States%2001.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "hi",
    "slug": "hi",
    "name": "Hawaii",
    "abbreviation": "HI",
    "capital": "Honolulu",
    "isoCode": "US-HI",
    "wikidataQid": "Q782",
    "commonsCategory": "Hawaii",
    "flag": {
      "file": "File:Flag of Hawaii.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Hawaii.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of the State of Hawaii.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20the%20State%20of%20Hawaii.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2020 Hawaii State Capitol 01.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2020%20Hawaii%20State%20Capitol%2001.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "id",
    "slug": "id",
    "name": "Idaho",
    "abbreviation": "ID",
    "capital": "Boise",
    "isoCode": "US-ID",
    "wikidataQid": "Q1221",
    "commonsCategory": "Idaho",
    "flag": {
      "file": "File:Flag of Idaho.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Idaho.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Idaho.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Idaho.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Bait on tree Idaho 8 January 2025.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bait%20on%20tree%20Idaho%208%20January%202025.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "il",
    "slug": "il",
    "name": "Illinois",
    "abbreviation": "IL",
    "capital": "Springfield",
    "isoCode": "US-IL",
    "wikidataQid": "Q1204",
    "commonsCategory": "Illinois",
    "flag": {
      "file": "File:Flag of Illinois.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Illinois.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Illinois.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Illinois.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Ardea herodias -Illinois, USA -flying-8.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Ardea%20herodias%20-Illinois%2C%20USA%20-flying-8.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "in",
    "slug": "in",
    "name": "Indiana",
    "abbreviation": "IN",
    "capital": "Indianapolis",
    "isoCode": "US-IN",
    "wikidataQid": "Q1415",
    "commonsCategory": "Indiana",
    "flag": {
      "file": "File:Flag of Indiana.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Indiana.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of the State of Indiana.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20the%20State%20of%20Indiana.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1816-1836 Executive Proceedings of the State of Indiana - DPLA - ca11da83da20123f7baab2a57c187403 (page 114).jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1816-1836%20Executive%20Proceedings%20of%20the%20State%20of%20Indiana%20-%20DPLA%20-%20ca11da83da20123f7baab2a57c187403%20(page%20114).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ia",
    "slug": "ia",
    "name": "Iowa",
    "abbreviation": "IA",
    "capital": "Des Moines",
    "isoCode": "US-IA",
    "wikidataQid": "Q1546",
    "commonsCategory": "Iowa",
    "flag": {
      "file": "File:Flag of Iowa.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Iowa.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:State seal of Iowa.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/State%20seal%20of%20Iowa.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1927 Iowa primary road system map.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1927%20Iowa%20primary%20road%20system%20map.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ks",
    "slug": "ks",
    "name": "Kansas",
    "abbreviation": "KS",
    "capital": "Topeka",
    "isoCode": "US-KS",
    "wikidataQid": "Q1558",
    "commonsCategory": "Kansas",
    "flag": {
      "file": "File:Flag of Kansas.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Kansas.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Kansas.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Kansas.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1992 Kansas United States House of Representatives election by Congressional District.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1992%20Kansas%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ky",
    "slug": "ky",
    "name": "Kentucky",
    "abbreviation": "KY",
    "capital": "Frankfort",
    "isoCode": "US-KY",
    "wikidataQid": "Q1603",
    "commonsCategory": "Kentucky",
    "flag": {
      "file": "File:Flag of Kentucky.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Kentucky.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Kentucky.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Kentucky.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Barclay, David - State- Kentucky - Regiment- 15 (Slaughter's) Kentucky Militia - DPLA - 5361494a887a6cec24a699e723d987d2.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Barclay%2C%20David%20-%20State-%20Kentucky%20-%20Regiment-%2015%20(Slaughter's)%20Kentucky%20Militia%20-%20DPLA%20-%205361494a887a6cec24a699e723d987d2.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "la",
    "slug": "la",
    "name": "Louisiana",
    "abbreviation": "LA",
    "capital": "Baton Rouge",
    "isoCode": "US-LA",
    "wikidataQid": "Q1588",
    "commonsCategory": "Louisiana",
    "flag": {
      "file": "File:Flag of Louisiana.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Louisiana.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Louisiana.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Louisiana.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1930 United States Senate Election in Louisiana Democratic Primary Results.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1930%20United%20States%20Senate%20Election%20in%20Louisiana%20Democratic%20Primary%20Results.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "me",
    "slug": "me",
    "name": "Maine",
    "abbreviation": "ME",
    "capital": "Augusta",
    "isoCode": "US-ME",
    "wikidataQid": "Q724",
    "commonsCategory": "Maine",
    "flag": {
      "file": "File:Flag of Maine.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Maine.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Maine.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Maine.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2021-07-20 02 Maine Marine Patrol Boat at Winter Harbor ME USA.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2021-07-20%2002%20Maine%20Marine%20Patrol%20Boat%20at%20Winter%20Harbor%20ME%20USA.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "md",
    "slug": "md",
    "name": "Maryland",
    "abbreviation": "MD",
    "capital": "Annapolis",
    "isoCode": "US-MD",
    "wikidataQid": "Q1391",
    "commonsCategory": "Maryland",
    "flag": {
      "file": "File:Flag of Maryland.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Maryland.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Maryland (reverse).svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Maryland%20(reverse).svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2016-05-18 13 50 21 View south along Oakley Road (Maryland State Route 470) near Colton Point Road (Maryland State Route 242) in Dynard, St. Mary's County, Maryland.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2016-05-18%2013%2050%2021%20View%20south%20along%20Oakley%20Road%20(Maryland%20State%20Route%20470)%20near%20Colton%20Point%20Road%20(Maryland%20State%20Route%20242)%20in%20Dynard%2C%20St.%20Mary's%20County%2C%20Maryland.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ma",
    "slug": "ma",
    "name": "Massachusetts",
    "abbreviation": "MA",
    "capital": "Boston",
    "isoCode": "US-MA",
    "wikidataQid": "Q771",
    "commonsCategory": "Massachusetts",
    "flag": {
      "file": "File:Flag of Massachusetts.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Massachusetts.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Massachusetts.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Massachusetts.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1713 border map of Massachusetts and Connecticut.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1713%20border%20map%20of%20Massachusetts%20and%20Connecticut.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "mi",
    "slug": "mi",
    "name": "Michigan",
    "abbreviation": "MI",
    "capital": "Lansing",
    "isoCode": "US-MI",
    "wikidataQid": "Q1166",
    "commonsCategory": "Michigan",
    "flag": {
      "file": "File:Flag of Michigan.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Michigan.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Michigan.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Michigan.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1899 Michigan Wolverines football team.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1899%20Michigan%20Wolverines%20football%20team.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "mn",
    "slug": "mn",
    "name": "Minnesota",
    "abbreviation": "MN",
    "capital": "Saint Paul",
    "isoCode": "US-MN",
    "wikidataQid": "Q1527",
    "commonsCategory": "Minnesota",
    "flag": {
      "file": "File:Flag of Minnesota.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Minnesota.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Minnesota.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Minnesota.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:\"The Courtship of Miles Standish\" at Mankato State Normal School, Mankato, Minnesota - DPLA - 1c511c9df643b7c1d3301eda7b0d9e27.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/%22The%20Courtship%20of%20Miles%20Standish%22%20at%20Mankato%20State%20Normal%20School%2C%20Mankato%2C%20Minnesota%20-%20DPLA%20-%201c511c9df643b7c1d3301eda7b0d9e27.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ms",
    "slug": "ms",
    "name": "Mississippi",
    "abbreviation": "MS",
    "capital": "Jackson",
    "isoCode": "US-MS",
    "wikidataQid": "Q1494",
    "commonsCategory": "Mississippi (state)",
    "flag": {
      "file": "File:Flag of Mississippi.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Mississippi.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Mississippi.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Mississippi.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:\"Don't Stone Her until You Hear Her Side\" Mississippi State Sovereignty Commission 1956 pamphlet.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/%22Don't%20Stone%20Her%20until%20You%20Hear%20Her%20Side%22%20Mississippi%20State%20Sovereignty%20Commission%201956%20pamphlet.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "mo",
    "slug": "mo",
    "name": "Missouri",
    "abbreviation": "MO",
    "capital": "Jefferson City",
    "isoCode": "US-MO",
    "wikidataQid": "Q1581",
    "commonsCategory": "Missouri",
    "flag": {
      "file": "File:Flag of Missouri.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Missouri.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Missouri.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Missouri.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2019 Missouri State Capitol 01.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2019%20Missouri%20State%20Capitol%2001.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "mt",
    "slug": "mt",
    "name": "Montana",
    "abbreviation": "MT",
    "capital": "Helena",
    "isoCode": "US-MT",
    "wikidataQid": "Q1212",
    "commonsCategory": "Montana",
    "flag": {
      "file": "File:Flag of Montana.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Montana.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Montana.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Montana.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:18891109 We Crow for Montana - The Butte Daily Miner.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/18891109%20We%20Crow%20for%20Montana%20-%20The%20Butte%20Daily%20Miner.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ne",
    "slug": "ne",
    "name": "Nebraska",
    "abbreviation": "NE",
    "capital": "Lincoln",
    "isoCode": "US-NE",
    "wikidataQid": "Q1553",
    "commonsCategory": "Nebraska",
    "flag": {
      "file": "File:Flag of Nebraska.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Nebraska.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of the State of Nebraska.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20the%20State%20of%20Nebraska.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:4th Nebraska Infantry Regimental Flag (1916).png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/4th%20Nebraska%20Infantry%20Regimental%20Flag%20(1916).png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "nv",
    "slug": "nv",
    "name": "Nevada",
    "abbreviation": "NV",
    "capital": "Carson City",
    "isoCode": "US-NV",
    "wikidataQid": "Q1227",
    "commonsCategory": "Nevada",
    "flag": {
      "file": "File:Flag of Nevada.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Nevada.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:State Seal of Nevada.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/State%20Seal%20of%20Nevada.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2012-10-17 023 View southeast along Nevada State Route 229 (Secret Pass Road) 26.5 miles from Interstate 80 in Elko County, Nevada.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2012-10-17%20023%20View%20southeast%20along%20Nevada%20State%20Route%20229%20(Secret%20Pass%20Road)%2026.5%20miles%20from%20Interstate%2080%20in%20Elko%20County%2C%20Nevada.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "nh",
    "slug": "nh",
    "name": "New Hampshire",
    "abbreviation": "NH",
    "capital": "Concord",
    "isoCode": "US-NH",
    "wikidataQid": "Q759",
    "commonsCategory": "New Hampshire",
    "flag": {
      "file": "File:Flag of New Hampshire.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20New%20Hampshire.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of New Hampshire.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20New%20Hampshire.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:(New Hampshire) Dunham, German - 14th Infantry, Company A - DPLA - b292127a7393c36a4ec33d531e9b38b4.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/(New%20Hampshire)%20Dunham%2C%20German%20-%2014th%20Infantry%2C%20Company%20A%20-%20DPLA%20-%20b292127a7393c36a4ec33d531e9b38b4.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "nj",
    "slug": "nj",
    "name": "New Jersey",
    "abbreviation": "NJ",
    "capital": "Trenton",
    "isoCode": "US-NJ",
    "wikidataQid": "Q1408",
    "commonsCategory": "New Jersey",
    "flag": {
      "file": "File:Flag of New Jersey.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20New%20Jersey.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of New Jersey.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20New%20Jersey.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2009-08-17 View of downtown Trenton in New Jersey and the mouth of the Assunpink Creek from across the Delaware River in Morrisville, Pennsylvania.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2009-08-17%20View%20of%20downtown%20Trenton%20in%20New%20Jersey%20and%20the%20mouth%20of%20the%20Assunpink%20Creek%20from%20across%20the%20Delaware%20River%20in%20Morrisville%2C%20Pennsylvania.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "nm",
    "slug": "nm",
    "name": "New Mexico",
    "abbreviation": "NM",
    "capital": "Santa Fe",
    "isoCode": "US-NM",
    "wikidataQid": "Q1522",
    "commonsCategory": "New Mexico",
    "flag": {
      "file": "File:Flag of New Mexico.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20New%20Mexico.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of New Mexico.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20New%20Mexico.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2002-2006 New Mexico United States House of Representatives election by Congressional District (no margins).png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2002-2006%20New%20Mexico%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District%20(no%20margins).png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ny",
    "slug": "ny",
    "name": "New York",
    "abbreviation": "NY",
    "capital": "Albany",
    "isoCode": "US-NY",
    "wikidataQid": "Q1384",
    "commonsCategory": "New York (state)",
    "flag": {
      "file": "File:Flag of New York.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20New%20York.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of New York (state).svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20New%20York%20(state).svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": {
      "file": "File:New York 1911.webm",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/New%20York%201911.webm",
      "source": "Wikimedia Commons"
    },
    "heroPhoto": {
      "file": "File:1 New York Plaza (24280p).jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1%20New%20York%20Plaza%20(24280p).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "nc",
    "slug": "nc",
    "name": "North Carolina",
    "abbreviation": "NC",
    "capital": "Raleigh",
    "isoCode": "US-NC",
    "wikidataQid": "Q1454",
    "commonsCategory": "North Carolina",
    "flag": {
      "file": "File:Flag of North Carolina.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20North%20Carolina.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of North Carolina.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20North%20Carolina.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:\"State Capitol\" Historical Marker.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/%22State%20Capitol%22%20Historical%20Marker.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "nd",
    "slug": "nd",
    "name": "North Dakota",
    "abbreviation": "ND",
    "capital": "Bismarck",
    "isoCode": "US-ND",
    "wikidataQid": "Q1207",
    "commonsCategory": "North Dakota",
    "flag": {
      "file": "File:Flag of North Dakota.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20North%20Dakota.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Great Seal of North Dakota.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Great%20Seal%20of%20North%20Dakota.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Aerial view of North Dakota 2025.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20North%20Dakota%202025.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "oh",
    "slug": "oh",
    "name": "Ohio",
    "abbreviation": "OH",
    "capital": "Columbus",
    "isoCode": "US-OH",
    "wikidataQid": "Q1397",
    "commonsCategory": "Ohio",
    "flag": {
      "file": "File:Flag of Ohio.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Ohio.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Ohio (B&W).svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Ohio%20(B%26W).svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Bird's-eye view of Ohio State University - DPLA - 6f62da88ad3c6ec3db9b73ab2ceb209a (page 1).jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Bird's-eye%20view%20of%20Ohio%20State%20University%20-%20DPLA%20-%206f62da88ad3c6ec3db9b73ab2ceb209a%20(page%201).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ok",
    "slug": "ok",
    "name": "Oklahoma",
    "abbreviation": "OK",
    "capital": "Oklahoma City",
    "isoCode": "US-OK",
    "wikidataQid": "Q1649",
    "commonsCategory": "Oklahoma",
    "flag": {
      "file": "File:Flag of Oklahoma.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Oklahoma.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Oklahoma.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Oklahoma.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:\"Colored\" drinking fountain from mid-20th century with african-american drinking.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/%22Colored%22%20drinking%20fountain%20from%20mid-20th%20century%20with%20african-american%20drinking.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "or",
    "slug": "or",
    "name": "Oregon",
    "abbreviation": "OR",
    "capital": "Salem",
    "isoCode": "US-OR",
    "wikidataQid": "Q824",
    "commonsCategory": "Oregon",
    "flag": {
      "file": "File:Flag of Oregon.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Oregon.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Oregon.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Oregon.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": {
      "file": "File:Aerial views of Oregon, United States in summer.webm",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20views%20of%20Oregon%2C%20United%20States%20in%20summer.webm",
      "source": "Wikimedia Commons"
    },
    "heroPhoto": {
      "file": "File:1966 Oregon Ducks Oregon State Beavers track and field dual meet.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1966%20Oregon%20Ducks%20Oregon%20State%20Beavers%20track%20and%20field%20dual%20meet.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "pa",
    "slug": "pa",
    "name": "Pennsylvania",
    "abbreviation": "PA",
    "capital": "Harrisburg",
    "isoCode": "US-PA",
    "wikidataQid": "Q1400",
    "commonsCategory": "Pennsylvania",
    "flag": {
      "file": "File:Flag of Pennsylvania.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Pennsylvania.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Pennsylvania.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Pennsylvania.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1923 Penn State Soccer Team.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1923%20Penn%20State%20Soccer%20Team.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ri",
    "slug": "ri",
    "name": "Rhode Island",
    "abbreviation": "RI",
    "capital": "Providence",
    "isoCode": "US-RI",
    "wikidataQid": "Q1387",
    "commonsCategory": "Rhode Island",
    "flag": {
      "file": "File:Flag of Rhode Island.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Rhode%20Island.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Rhode Island (2021).svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Rhode%20Island%20(2021).svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2019 Rhode Island State House 01.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2019%20Rhode%20Island%20State%20House%2001.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "sc",
    "slug": "sc",
    "name": "South Carolina",
    "abbreviation": "SC",
    "capital": "Columbia",
    "isoCode": "US-SC",
    "wikidataQid": "Q1456",
    "commonsCategory": "South Carolina",
    "flag": {
      "file": "File:Flag of South Carolina.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20South%20Carolina.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of South Carolina.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20South%20Carolina.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1986-1990 South Carolina United States House of Representatives election by Congressional District (no margins).png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1986-1990%20South%20Carolina%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District%20(no%20margins).png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "sd",
    "slug": "sd",
    "name": "South Dakota",
    "abbreviation": "SD",
    "capital": "Pierre",
    "isoCode": "US-SD",
    "wikidataQid": "Q1211",
    "commonsCategory": "South Dakota",
    "flag": {
      "file": "File:Flag of South Dakota.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20South%20Dakota.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:State Seal of South Dakota.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/State%20Seal%20of%20South%20Dakota.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:Cornerstone, South Dakota State Capitol, Capitol Avenue, Pierre, SD.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cornerstone%2C%20South%20Dakota%20State%20Capitol%2C%20Capitol%20Avenue%2C%20Pierre%2C%20SD.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "tn",
    "slug": "tn",
    "name": "Tennessee",
    "abbreviation": "TN",
    "capital": "Nashville",
    "isoCode": "US-TN",
    "wikidataQid": "Q1509",
    "commonsCategory": "Tennessee",
    "flag": {
      "file": "File:Flag of Tennessee.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Tennessee.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Tennessee.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Tennessee.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1994-2000 Tennessee United States House of Representatives election by Congressional District.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1994-2000%20Tennessee%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "tx",
    "slug": "tx",
    "name": "Texas",
    "abbreviation": "TX",
    "capital": "Austin",
    "isoCode": "US-TX",
    "wikidataQid": "Q1439",
    "commonsCategory": "Texas",
    "flag": {
      "file": "File:Flag of Texas.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Texas.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Texas.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Texas.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2025 Texas State Capitol 01.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2025%20Texas%20State%20Capitol%2001.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "ut",
    "slug": "ut",
    "name": "Utah",
    "abbreviation": "UT",
    "capital": "Salt Lake City",
    "isoCode": "US-UT",
    "wikidataQid": "Q829",
    "commonsCategory": "Utah",
    "flag": {
      "file": "File:Flag of Utah.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Utah.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Utah.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Utah.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2019 Utah State Capitol 01.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2019%20Utah%20State%20Capitol%2001.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "vt",
    "slug": "vt",
    "name": "Vermont",
    "abbreviation": "VT",
    "capital": "Montpelier",
    "isoCode": "US-VT",
    "wikidataQid": "Q16551",
    "commonsCategory": "Vermont",
    "flag": {
      "file": "File:Flag of Vermont.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Vermont.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:State Seal of Vermont.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/State%20Seal%20of%20Vermont.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2022-04 Vermont State House 02.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2022-04%20Vermont%20State%20House%2002.jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "va",
    "slug": "va",
    "name": "Virginia",
    "abbreviation": "VA",
    "capital": "Richmond",
    "isoCode": "US-VA",
    "wikidataQid": "Q1370",
    "commonsCategory": "Virginia",
    "flag": {
      "file": "File:Flag of Virginia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Virginia.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Virginia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Virginia.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1998 Virginia United States House of Representatives election by Congressional District.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1998%20Virginia%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "wa",
    "slug": "wa",
    "name": "Washington",
    "abbreviation": "WA",
    "capital": "Olympia",
    "isoCode": "US-WA",
    "wikidataQid": "Q1223",
    "commonsCategory": "Washington (state)",
    "flag": {
      "file": "File:Flag of Washington.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Washington.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Washington.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Washington.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1928 Washington State Senate District Map.png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1928%20Washington%20State%20Senate%20District%20Map.png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "wv",
    "slug": "wv",
    "name": "West Virginia",
    "abbreviation": "WV",
    "capital": "Charleston",
    "isoCode": "US-WV",
    "wikidataQid": "Q1371",
    "commonsCategory": "West Virginia",
    "flag": {
      "file": "File:Flag of West Virginia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20West%20Virginia.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of West Virginia.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20West%20Virginia.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1982-1990 West Virginia United States House of Representatives election by Congressional District (no margins).png",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1982-1990%20West%20Virginia%20United%20States%20House%20of%20Representatives%20election%20by%20Congressional%20District%20(no%20margins).png",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "wi",
    "slug": "wi",
    "name": "Wisconsin",
    "abbreviation": "WI",
    "capital": "Madison",
    "isoCode": "US-WI",
    "wikidataQid": "Q1537",
    "commonsCategory": "Wisconsin",
    "flag": {
      "file": "File:Flag of Wisconsin.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Wisconsin.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Wisconsin.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Wisconsin.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:2022 Wisconsin State Fair 38 (Wisconsin Products Pavilion).jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/2022%20Wisconsin%20State%20Fair%2038%20(Wisconsin%20Products%20Pavilion).jpg",
      "source": "Wikimedia Commons"
    }
  },
  {
    "id": "wy",
    "slug": "wy",
    "name": "Wyoming",
    "abbreviation": "WY",
    "capital": "Cheyenne",
    "isoCode": "US-WY",
    "wikidataQid": "Q1214",
    "commonsCategory": "Wyoming",
    "flag": {
      "file": "File:Flag of Wyoming.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag%20of%20Wyoming.svg",
      "source": "Wikimedia Commons"
    },
    "seal": {
      "file": "File:Seal of Wyoming.svg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/Seal%20of%20Wyoming.svg",
      "source": "Wikimedia Commons"
    },
    "heroVideo": null,
    "heroPhoto": {
      "file": "File:1883 Holt's New Map of Wyoming.jpg",
      "url": "https://commons.wikimedia.org/wiki/Special:FilePath/1883%20Holt's%20New%20Map%20of%20Wyoming.jpg",
      "source": "Wikimedia Commons"
    }
  }
]

